---

- name: "Install Docker"
  become: true
  shell: |
    sudo snap install docker

- name: "Install Pip3"
  become: true
  apt:
    name: ["python3-pip"]
    state: latest
    update_cache: yes

- name: "Installing Project Dependencies and Running"
  shell: |
    sudo apt-get update
    sudo snap install docker
    sudo apt install git
    git clone https://github.com/dravellar/ksgstore.git
    cd ksgstore
    sudo docker compose up

# - name: "move en variable to /etc/profile.d/"
#   become: true
#   copy:
#     src: ../files/myenv.sh
#     dest: /etc/profile.d/