---

- name: "Installing Project Dependencies and Running"
  shell: |
    sudo apt-get update
    sudo snap install docker
    sudo apt install git
    git clone https://github.com/dravellar/ksgstore.git
    cd ksgstore
    sudo docker compose up